version: 2

jobs:

    integrate:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox
                ./resources/gcp-install.sh
                gcloud beta emulators pubsub start --project="i3-gcp-proj" &
                tox integrate_tests -vv

    examples:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox
                tox --notest -vv
                . .tox/py/bin/activate
                echo "First, NATS's Examples:"
                cd ./
                python ./examples/nats_examples/nats_jetstream.py
                echo "Now, Our Examples:"
                echo "TODO"


    pycycle:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox pycycle
                tox --notest -vv
                . .tox/py/bin/activate
                pycycle --here --verbose


workflows:
    version: 2
    build_and_test:
        jobs:
            - integrate
            - examples
            - pycycle